name: CI

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest pytest-bdd ruff mypy

      - name: Ruff check
        run: python3 -m ruff check . --fix

      - name: Ruff format
        run: python3 -m ruff format . --check

      - name: Unit tests
        run: python3 -m pytest ./core/tests/unit

      - name: Integration tests
        run: python3 -m pytest ./core/tests/integration

      - name: BDD tests
        run: python3 -m pytest ./core/tests/behaviour